### ISSUE TITLE
Tasks of Review

### ISSUE THREAD

**Issue by QC-L** [reactjs/zh-hans.react.dev#684]
# Review 任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
>
> 2. 请按 [排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97) 进行 Review，如发现过多排版问题可直接 PR 打回重改。

**注意：每个评论只能有一条任务，如有多条，请分开评论，保证评论数与任务数一致**。

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] index #602

领取过：

* [ ] index #602 (@QC-L)

领取过，已完成：

* [x] index #602 (@QC-L) 

**领取方式，在本 issues 下评论即可。**

认领 Review 任务格式：

```markdown
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  index | @QC-L | 2021.12.08 - 2021.12.10 | -
```

示例效果：

Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  index | @QC-L | 2021.12.08 - 2021.12.10 | -

当完成时，请通知原 PR 作者，并修改 PR。

Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  index | @QC-L | 2021.12.08 - 2021.12.10 | ✅

## 任务认领列表

Todo List:

- [x] [index](https://github.com/reactjs/zh-hans.react.dev/blob/main/src/components/Layout/HomeContent.js) #1087 

- [ ] learn
  - [x] [add-react-to-a-website](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/add-react-to-a-website.md) #640 
  - [ ] [add-react-to-an-existing-project](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/add-react-to-an-existing-project.md)
  - [x] [adding-interactivity](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/adding-interactivity.md) #1053 
  - [ ] [choosing-the-state-structure](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/choosing-the-state-structure.md) #1094 
  - [x] [conditional-rendering](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/conditional-rendering.md) #636 
  - [x] [describing-the-ui](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/describing-the-ui.md) #650 
  - [x] [editor-setup](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/editor-setup.md) #633 
  - [ ] [escape-hatches](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/escape-hatches.md)
  - [x] [extracting-state-logic-into-a-reducer](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/extracting-state-logic-into-a-reducer.md) #693 
  - [ ] [importing-and-exporting-components](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/importing-and-exporting-components.md)
  - [x] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/index.md) #696 
  - [x] [installation](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/installation.md) #607 
  - [x] [javascript-in-jsx-with-curly-braces](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/javascript-in-jsx-with-curly-braces.md) #672 
  - [x] [keeping-components-pure](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/keeping-components-pure.md) #642 
  - [ ] [lifecycle-of-reactive-effects](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/lifecycle-of-reactive-effects.md)
  - [x] [managing-state](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/managing-state.md) #653 
  - [x] [manipulating-the-dom-with-refs](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/manipulating-the-dom-with-refs.md) #665 
  - [x] [passing-data-deeply-with-context](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/passing-data-deeply-with-context.md) #675 
  - [x] [passing-props-to-a-component](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/passing-props-to-a-component.md) #647 
  - [x] [preserving-and-resetting-state](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/preserving-and-resetting-state.md) #679 
  - [x] [queueing-a-series-of-state-updates](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/queueing-a-series-of-state-updates.md) #677 
  - [x] [react-developer-tools](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/react-developer-tools.md) #644 
  - [x] [reacting-to-input-with-state](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/reacting-to-input-with-state.md) #692 
  - [x] [referencing-values-with-refs](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/referencing-values-with-refs.md) #649 
  - [ ] [removing-effect-dependencies](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/removing-effect-dependencies.md)
  - [x] [render-and-commit](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/render-and-commit.md) #686 
  - [x] [rendering-lists](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/rendering-lists.md) #676 
  - [x] [responding-to-events](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/responding-to-events.md) #635 
  - [ ] [reusing-logic-with-custom-hooks](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/reusing-logic-with-custom-hooks.md)
  - [x] [scaling-up-with-reducer-and-context](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/scaling-up-with-reducer-and-context.md) #694 
  - [ ] [separating-events-from-effects](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/separating-events-from-effects.md)
  - [x] [sharing-state-between-components](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/sharing-state-between-components.md) #652 
  - [x] [start-a-new-react-project](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/start-a-new-react-project.md) #1111 
  - [x] [state-a-components-memory](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/state-a-components-memory.md) #651 
  - [x] [state-as-a-snapshot](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/state-as-a-snapshot.md) #643 
  - [ ] [synchronizing-with-effects](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/synchronizing-with-effects.md)
  - [x] [thinking-in-react](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/thinking-in-react.md) #682 
  - [ ] [tutorial-tic-tac-toe](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/tutorial-tic-tac-toe.md) #1116
  - [x] [updating-arrays-in-state](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/updating-arrays-in-state.md) #654 
  - [ ] [updating-objects-in-state](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/updating-objects-in-state.md) 
  - [x] [writing-markup-with-jsx](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/writing-markup-with-jsx.md) #673
  - [ ] [you-might-not-need-an-effect](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/you-might-not-need-an-effect.md)
  - [x] [your-first-component](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/learn/your-first-component.md) #641 

- [ ] reference
  - [ ] react-dom
    - [ ] client
      - [ ] [createRoot](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/client/createRoot.md)
      - [ ] [hydrateRoot](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/client/hydrateRoot.md)
      - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/client/index.md)
    - [ ] components
      - [ ] [common](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/common.md)
      - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/index.md)
      - [ ] [input](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/input.md)
      - [ ] [option](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/option.md)
      - [ ] [progress](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/progress.md)
      - [ ] [select](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/select.md)
      - [ ] [textarea](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/components/textarea.md)
    - [ ] server
      - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/index.md)
      - [ ] [renderToNodeStream](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToNodeStream.md)
      - [ ] [renderToPipeableStream](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToPipeableStream.md)
      - [ ] [renderToReadableStream](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToReadableStream.md)
      - [ ] [renderToStaticMarkup](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToStaticMarkup.md)
      - [ ] [renderToStaticNodeStream](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToStaticNodeStream.md)
      - [ ] [renderToString](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/server/renderToString.md)
    - [ ] [createPortal](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/createPortal.md)
    - [ ] [findDOMNode](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/findDOMNode.md)
    - [ ] [flushSync](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/flushSync.md)
    - [ ] [hydrate](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/hydrate.md)
    - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/index.md)
    - [x] [render](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/render.md) #632 
    - [ ] [unmountComponentAtNode](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react-dom/unmountComponentAtNode.md)
  - [ ] react
    - [ ] [apis](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/apis.md)
    - [ ] [Children](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/Children.md)
    - [ ] [cloneElement](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/cloneElement.md)
    - [ ] [Component](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/Component.md)
    - [ ] [components](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/components.md)
    - [x] [createContext](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/createContext.md) #1120 
    - [ ] [createElement](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/createElement.md)
    - [ ] [createFactory](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/createFactory.md)
    - [ ] [createRef](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/createRef.md)
    - [ ] [experimental_useEffectEvent](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/experimental_useEffectEvent.md)
    - [ ] [forwardRef](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/forwardRef.md)
    - [ ] [Fragment](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/Fragment.md)
    - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/index.md) 
    - [ ] [isValidElement](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/isValidElement.md)
    - [x] [lazy](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/lazy.md) #1101 
    - [ ] [legacy](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/legacy.md)
    - [ ] [memo](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/memo.md)
    - [ ] [Profiler](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/Profiler.md)
    - [ ] [PureComponent](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/PureComponent.md)
    - [ ] [startTransition](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/startTransition.md) #1104 
    - [ ] [StrictMode](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/StrictMode.md)
    - [ ] [Suspense](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/Suspense.md)
    - [ ] [useCallback](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useCallback.md)
    - [ ] [useContext](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useContext.md) #1097 
    - [ ] [useDebugValue](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useDebugValue.md)
    - [ ] [useDeferredValue](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useDeferredValue.md)
    - [ ] [useEffect](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useEffect.md) #1122 
    - [ ] [useId](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useId.md) #1108 
    - [x] [useImperativeHandle](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useImperativeHandle.md) #1123 
    - [ ] [useInsertionEffect](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useInsertionEffect.md)
    - [ ] [useLayoutEffect](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useLayoutEffect.md) #1106 
    - [ ] [useMemo](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useMemo.md)
    - [ ] [useReducer](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useReducer.md)
    - [ ] [useRef](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useRef.md)
    - [ ] [useState](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useState.md)
    - [ ] [useSyncExternalStore](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useSyncExternalStore.md)
    - [ ] [useTransition](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/reference/react/useTransition.md)

- [ ] community
  - [ ] [acknowledgements](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/acknowledgements.md)
  - [ ] [conferences](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/conferences.md)
  - [ ] [docs-contributors](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/docs-contributors.md)
  - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/index.md)
  - [ ] [meet-the-team](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/meet-the-team.md)
  - [ ] [meetups](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/meetups.md)
  - [ ] [team](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/team.md)
  - [ ] [versioning-policy](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/versioning-policy.md)
  - [ ] [videos](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/community/videos.md)

- [ ] blog
  - [ ] [index](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/index.md)
  - [ ] 2020/12/21
    - [ ] [data-fetching-with-react-server-components](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2020/12/21/data-fetching-with-react-server-components.md)
  - [ ] 2021
    - [ ] 06/08
      - [ ] [the-plan-for-react-18](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2021/06/08/the-plan-for-react-18.md)
    - [ ] 12/17
      - [ ] [react-conf-2021-recap](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2021/12/17/react-conf-2021-recap.md)
  - [ ] 2022
    - [ ] 03
      - [ ] 08
        - [ ] [react-18-upgrade-guide](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2022/03/08/react-18-upgrade-guide.md)
      - [ ] 29
        - [ ] [react-v18](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2022/03/29/react-v18.md)
    - [ ] 06/15
      - [ ] [react-labs-what-we-have-been-working-on-june-2022](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md)
  - [ ] 2023/03
    - [ ] 16
      - [ ] [introducing-react-dev](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2023/03/16/introducing-react-dev.md)
    - [ ] 22
      - [ ]  [react-labs-what-we-have-been-working-on-march-2023](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023.md)

- [ ] warnings
  - [ ] [invalid-aria-prop](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/warnings/invalid-aria-prop.md)
  - [ ] [invalid-hook-call-warning](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/warnings/invalid-hook-call-warning.md)
  - [ ] [special-props](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/warnings/special-props.md)
  - [ ] [unknown-prop](https://github.com/reactjs/zh-hans.react.dev/tree/main/src/content/warnings/unknown-prop.md)

**Comment by HaroldHL** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  choosing-the-state-structure | @HaroldHL | 2021.12.08 - 2021.12.10 | -

**Comment by takeItIzzy** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  updating-arrays-in-state | @takeItIzzy | 2021.12.08 - 2021.12.10 | -

**Comment by nmsn** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | your-first-component | @nmsn | 2021.12.08 - 2021.12.10 | -

**Comment by lyanmm** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  managing-state | @lyanmm | 2021.12.08 - 2021.12.10 | -

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| API | reference/usestate | @watonyweng | 2021.12.08 - 2021.12.10 | - |

**Comment by lyj505** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  describing-the-ui | @lyj505 | 2021.12.08 - 2021.12.10 | -

**Comment by Ikaite** [comment]
<html>
<body>


Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | scaling-up-with-reducer-and-context | @Ikaite | 2021.12.6 - 2021.12.12 | -


</body>
</html>

**Comment by Megrax** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | javascript-in-jsx-with-curly-braces  | @Megrax | 2021.12.08 - 2021.12.10 | -

**Comment by QC-L** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  conditional-rendering | @QC-L | 2021.12.08 - 2021.12.10 | -

**Comment by ZhangDaZongWei** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | add-react-to-a-website | @ZhangDaZongWei | 2021.12.07 - 2021.12.09 | -

**Comment by yyyang1996** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  add-react-to-a-website | @yyyang1996  | 2021.12.08 - 2021.12.10 | -

**Comment by Hyuain** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
learn | keeping-components-pure | @Hyuain | 2021.12.08 - 2021.12.10 | -

**Comment by evan-lc** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
API Reference |  reactdom | @evan-lc | 2021.12.08 - 2021.12.10 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   referencing-values-with-refs  | @Neo42 | 2021.12.08 - 2021.12.10 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   preserving-and-resetting-state  | @Neo42 | 2021.12.08 - 2021.12.10 | -

**Comment by rottenpen** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  keeping-components-pure | @rottenpen | 2021.12.08 - 2021.12.10 | -

**Comment by Davont** [comment]
<html>
<body>


Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
API Reference |  index | @davont| 2021.12.08 - 2021.12.10 | -


</body>
</html>

**Comment by rottenpen** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  passing-props-to-a-component | @rottenpen | 2021.12.09 - 2021.12.11 | -

**Comment by bingcoder** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   react-developer-tools  | @QC-L | 2021.12.08 - 2021.12.9 | -

**Comment by mffy** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  translate learn/index into Chinese | @mffy | 2021.12.09 - 2021.12.11 |   -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   choosing-the-state-structure  | @Neo42 | 2021.12.10 - 2021.12.12 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   state-as-a-snapshot  | @Neo42 | 2021.12.10 - 2021.12.12 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |    queueing-a-series-of-state-updates  | @Neo42 | 2021.12.10 - 2021.12.12 | -

**Comment by dearalina** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  react-developer-tools | @dearalina | 2021.12.10 - 2021.12.12 | -

**Comment by dearalina** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  sharing-state-between-components | @dearalina | 2021.12.10 - 2021.12.12 | -

**Comment by rottenpen** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  rendering-list | @rottenpen | 2021.12.12 - 2021.12.14 |

**Comment by sooia** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
Api Reference | translation api index done  | @sooia | 2021.12.12 - 2021.12.15 |   -

**Comment by sooia** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | translate learn/index into Chinese | @sooia | 2021.12.12 - 2021.12.14 | -

**Comment by sooia** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | translate learn/thinking-in-react | @sooia | 2021.12.13 - 2021.12.15 | -

**Comment by x-cold** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | state-a-components-memory | @x-cold | 2021.12.14 - 2021.12.16 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |     updating-objects-in-state  | @Neo42 | 2021.12.15 - 2021.12.17 | -

**Comment by sooia** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | start-a-new-react-project | @sooia | 2021.12.16 - 2021.12.18 | -

**Comment by yyyang1996** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  extracting-state-logic-into-a-reducer | @yyyang1996  | 2021.12.25 - 2021.12.27 | -

**Comment by Neo42** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |     render-and-commit   | @Neo42 | 2021.12.21 - 2021.12.23 |  ✅

**Comment by oceanlvr** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn | reacting-to-input-with-state | @oceanlvr | 2021.12.21 - 2021.12.25 | -

**Comment by takeItIzzy** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  scaling-up-with-reducer-and-context | @takeItIzzy | 2021.12.22 - 2021.12.26 | -

**Comment by KimYangOfCat** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   reacting-to-input-with-state | @KimYangOfCat | 2021.12.31 - 2021.12.31 | -

**Comment by KimYangOfCat** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |   render-and-commit  | @KimYangOfCat | 2021.12.31 - 2021.12.31 | ✅

**Comment by TinaaaaP** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  scaling-up-with-reducer-and-context | @Tina Pu | 2022.01.06 - 2022.01.08 | -

**Comment by TinaaaaP** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  render-and-commit | @TinaaaaP | 2022.01.15 - 2022.01.15 | ✅

**Comment by TinaaaaP** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  reacting-to-input-with-state | @TinaaaaP | 2022.01.15 - 2022.01.15 | ✅

**Comment by earthaYan** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
learn |  removing-effect-dependencies | @earthaYan | 2023.06.26- 2023.06.28 | -

**Comment by CoderSerio** [comment]
Section | Title | Reviewer | 完成时间 | 是否已完成
-- | -- | -- | -- | --
reference |  react-dom/client/hydrateRoot | @CoderSerio | 2023.06.26 - 2023.06.29 | -

**Comment by awxiaoxian2020** [comment]
Code Review 可以直接在 PR 进行。本 issue 长期未维护，考虑暂时关闭。
